name: CI tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    strategy:
      matrix:
        include:
          - ruby: '3.2'
            rails: '7.1'
          - ruby: '3.3'
            rails: '7.2'
          - ruby: '3.4'
            rails: '8.0'

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Generate Rails app
      run: bin/setup
    - name: Run unit tests
      run: bundle exec rake spec:unit
    - name: Run integration tests
      run: bundle exec rake spec:integration
